In [2]:
import pandas as pd

In [3]:
# --- Datasets ---

url_1 = "https://raw.githubusercontent.com/cgveradi/house_martell_project/main/data/raw/df_final_demo.txt" # Demographics Dataset
url_2 = "https://raw.githubusercontent.com/cgveradi/house_martell_project/main/data/raw/df_final_experiment_clients.txt" # Experiment Dataset
url_3_1 = "https://raw.githubusercontent.com/cgveradi/house_martell_project/main/data/raw/df_final_web_data_pt_1.txt" # Web_data part 1 Dataset
url_3_2 = "https://raw.githubusercontent.com/cgveradi/house_martell_project/main/data/raw/df_final_web_data_pt_2.txt" # Web_data part 2 Dataset

# --- Dataframes --- 

df_demo = pd.read_csv(url_1)
df_experiment = pd.read_csv(url_2)
df_web_pt1 = pd.read_csv(url_3_1)
df_web_pt2 = pd.read_csv(url_3_2)
    
    
print(f"df_demo shape: {df_demo.shape}")
print(f"df_experiment shape: {df_experiment.shape}")
print(f"df_web_pt1 shape: {df_web_pt1.shape}")
print(f"df_web_pt2 shape: {df_web_pt2.shape}")

df_demo shape: (70609, 9)
df_experiment shape: (70609, 2)
df_web_pt1 shape: (343141, 5)
df_web_pt2 shape: (412264, 5)

In [4]:
df_demo.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 70609 entries, 0 to 70608
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   client_id         70609 non-null  int64
 1   clnt_tenure_yr    70595 non-null  float64
 2   clnt_tenure_mnth  70595 non-null  float64
 3   clnt_age          70594 non-null  float64
 4   gendr             70595 non-null  object
 5   num_accts         70595 non-null  float64
 6   bal               70595 non-null  float64
 7   calls_6_mnth      70595 non-null  float64
 8   logons_6_mnth     70595 non-null  float64
dtypes: float64(7), int64(1), object(1)
memory usage: 4.8+ MB

In [5]:
df_demo

,client_id,clnt_tenure_yr,clnt_tenure_mnth,clnt_age,gendr,num_accts,bal,calls_6_mnth,logons_6_mnth
0,836976,6.0,73.0,60.5,U,2.0,45105.30,6.0,9.0
1,2304905,7.0,94.0,58.0,U,2.0,110860.30,6.0,9.0
2,1439522,5.0,64.0,32.0,U,2.0,52467.79,6.0,9.0
3,1562045,16.0,198.0,49.0,M,2.0,67454.65,3.0,6.0
4,5126305,12.0,145.0,33.0,F,2.0,103671.75,0.0,3.0
...,...,...,...,...,...,...,...,...,...
70604,7993686,4.0,56.0,38.5,U,3.0,1411062.68,5.0,5.0
70605,8981690,12.0,148.0,31.0,M,2.0,101867.07,6.0,6.0
70606,333913,16.0,198.0,61.5,F,2.0,40745.00,3.0,3.0
70607,1573142,21.0,255.0,68.0,M,3.0,475114.69,4.0,4.0
70608,5602139,21.0,254.0,59.5,F,3.0,157498.73,7.0,7.0

In [6]:
# --- Rename Columns in df_demo ---
# We observed that column names need adjustment for easy reading and use
df_demo.rename(columns={
    'clnt_age': 'age', 
    'gendr': 'gender', 
    'clnt_tenure_yr': 'tenure_yrs'}, inplace=True)

In [ ]:
df_experiment.info()

In [ ]:
df_experiment

In [ ]:
df_web_pt1.info()

In [ ]:
df_web_pt1

In [ ]:
df_web_pt2.info()

In [ ]:
df_web_pt2

In [7]:
# --- Combine and Clean Web Data ---
df_web = pd.concat([df_web_pt1, df_web_pt2], ignore_index=True)

In [8]:
# Convert date_time to datetime object 
df_web['date_time'] = pd.to_datetime(df_web['date_time'])

In [ ]:
df_web

In [9]:
print(df_web.duplicated().any())
print(df_web.duplicated().sum())

True
10764

In [10]:
# Drop duplicate web interaction records
initial_rows = len(df_web)
df_web.drop_duplicates(inplace=True)

In [ ]:
df_web

In [11]:
print(df_web.duplicated().any())
print(df_web.duplicated().sum())

False
0

In [12]:
# Sort chronologically 
df_web.sort_values(by=['client_id', 'date_time'], inplace=True)

In [13]:
# --- Merge Datasets ---

df_merged = pd.merge(df_web, df_experiment, on='client_id', how='left')

In [14]:
df_final = pd.merge(df_merged, df_demo, on='client_id', how='left')

In [15]:
df_final

,client_id,visitor_id,visit_id,process_step,date_time,Variation,tenure_yrs,clnt_tenure_mnth,age,gender,num_accts,bal,calls_6_mnth,logons_6_mnth
0,169,201385055_71273495308,749567106_99161211863_557568,start,2017-04-12 20:19:36,NaN,21.0,262.0,47.5,M,2.0,501570.72,4.0,4.0
1,169,201385055_71273495308,749567106_99161211863_557568,step_1,2017-04-12 20:19:45,NaN,21.0,262.0,47.5,M,2.0,501570.72,4.0,4.0
2,169,201385055_71273495308,749567106_99161211863_557568,step_2,2017-04-12 20:20:31,NaN,21.0,262.0,47.5,M,2.0,501570.72,4.0,4.0
3,169,201385055_71273495308,749567106_99161211863_557568,step_3,2017-04-12 20:22:05,NaN,21.0,262.0,47.5,M,2.0,501570.72,4.0,4.0
4,169,201385055_71273495308,749567106_99161211863_557568,confirm,2017-04-12 20:23:09,NaN,21.0,262.0,47.5,M,2.0,501570.72,4.0,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
744636,9999875,738878760_1556639849,931268933_219402947_599432,step_1,2017-06-01 22:40:08,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
744637,9999875,738878760_1556639849,931268933_219402947_599432,step_1,2017-06-01 22:41:28,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
744638,9999875,738878760_1556639849,931268933_219402947_599432,step_2,2017-06-01 22:41:47,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
744639,9999875,738878760_1556639849,931268933_219402947_599432,step_3,2017-06-01 22:44:58,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
744640,9999875,738878760_1556639849,931268933_219402947_599432,confirm,2017-06-01 22:48:39,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [16]:
df_final['Variation'].unique()

array([nan, 'Test', 'Control'], dtype=object)

In [9]:
print(df_final.duplicated().any())
print(df_final.duplicated().sum())

True
10764

In [17]:
df_clean = df_final.dropna(subset=['Variation']).drop_duplicates().copy()

df_clean.sort_values(by=['client_id', 'date_time'], inplace=True)

In [18]:
df_clean

,client_id,visitor_id,visit_id,process_step,date_time,Variation,tenure_yrs,clnt_tenure_mnth,age,gender,num_accts,bal,calls_6_mnth,logons_6_mnth
12,555,402506806_56087378777,637149525_38041617439_716659,start,2017-04-15 12:57:56,Test,3.0,46.0,29.5,U,2.0,25454.66,2.0,6.0
13,555,402506806_56087378777,637149525_38041617439_716659,step_1,2017-04-15 12:58:03,Test,3.0,46.0,29.5,U,2.0,25454.66,2.0,6.0
14,555,402506806_56087378777,637149525_38041617439_716659,step_2,2017-04-15 12:58:35,Test,3.0,46.0,29.5,U,2.0,25454.66,2.0,6.0
15,555,402506806_56087378777,637149525_38041617439_716659,step_3,2017-04-15 13:00:14,Test,3.0,46.0,29.5,U,2.0,25454.66,2.0,6.0
16,555,402506806_56087378777,637149525_38041617439_716659,confirm,2017-04-15 13:00:34,Test,3.0,46.0,29.5,U,2.0,25454.66,2.0,6.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
744612,9999729,834634258_21862004160,870243567_56915814033_814203,step_2,2017-05-08 16:08:40,Test,10.0,124.0,31.0,F,3.0,107059.74,6.0,9.0
744613,9999729,834634258_21862004160,870243567_56915814033_814203,step_3,2017-05-08 16:09:19,Test,10.0,124.0,31.0,F,3.0,107059.74,6.0,9.0
744614,9999729,834634258_21862004160,870243567_56915814033_814203,confirm,2017-05-08 16:09:40,Test,10.0,124.0,31.0,F,3.0,107059.74,6.0,9.0
744627,9999832,145538019_54444341400,472154369_16714624241_585315,start,2017-05-16 16:46:03,Test,23.0,281.0,49.0,F,2.0,431887.61,1.0,4.0
744628,9999832,145538019_54444341400,472154369_16714624241_585315,step_1,2017-05-16 16:46:11,Test,23.0,281.0,49.0,F,2.0,431887.61,1.0,4.0

In [12]:
print(df_clean.duplicated().any())
print(df_clean.duplicated().sum())

False
0

In [19]:
df_clean = df_clean.drop_duplicates()

In [ ]:
print(df_clean.duplicated().any())
print(df_clean.duplicated().sum())

In [20]:
df_clean['gender'] = df_clean['gender'].replace({'M': 'Male','F': 'Female','U': 'Unknown','X': 'Other'})

In [21]:
df_clean['gender'].nunique()

4

In [22]:
df_clean['gender'].value_counts()

gender
Unknown    107614
Male       106703
Female     102810
Other           8
Name: count, dtype: int64

In [23]:
df_clean['gender']

12        Unknown
13        Unknown
14        Unknown
15        Unknown
16        Unknown
           ...
744612     Female
744613     Female
744614     Female
744627     Female
744628     Female
Name: gender, Length: 317235, dtype: object

In [24]:
df_clean

,client_id,visitor_id,visit_id,process_step,date_time,Variation,tenure_yrs,clnt_tenure_mnth,age,gender,num_accts,bal,calls_6_mnth,logons_6_mnth
12,555,402506806_56087378777,637149525_38041617439_716659,start,2017-04-15 12:57:56,Test,3.0,46.0,29.5,Unknown,2.0,25454.66,2.0,6.0
13,555,402506806_56087378777,637149525_38041617439_716659,step_1,2017-04-15 12:58:03,Test,3.0,46.0,29.5,Unknown,2.0,25454.66,2.0,6.0
14,555,402506806_56087378777,637149525_38041617439_716659,step_2,2017-04-15 12:58:35,Test,3.0,46.0,29.5,Unknown,2.0,25454.66,2.0,6.0
15,555,402506806_56087378777,637149525_38041617439_716659,step_3,2017-04-15 13:00:14,Test,3.0,46.0,29.5,Unknown,2.0,25454.66,2.0,6.0
16,555,402506806_56087378777,637149525_38041617439_716659,confirm,2017-04-15 13:00:34,Test,3.0,46.0,29.5,Unknown,2.0,25454.66,2.0,6.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
744612,9999729,834634258_21862004160,870243567_56915814033_814203,step_2,2017-05-08 16:08:40,Test,10.0,124.0,31.0,Female,3.0,107059.74,6.0,9.0
744613,9999729,834634258_21862004160,870243567_56915814033_814203,step_3,2017-05-08 16:09:19,Test,10.0,124.0,31.0,Female,3.0,107059.74,6.0,9.0
744614,9999729,834634258_21862004160,870243567_56915814033_814203,confirm,2017-05-08 16:09:40,Test,10.0,124.0,31.0,Female,3.0,107059.74,6.0,9.0
744627,9999832,145538019_54444341400,472154369_16714624241_585315,start,2017-05-16 16:46:03,Test,23.0,281.0,49.0,Female,2.0,431887.61,1.0,4.0
744628,9999832,145538019_54444341400,472154369_16714624241_585315,step_1,2017-05-16 16:46:11,Test,23.0,281.0,49.0,Female,2.0,431887.61,1.0,4.0

In [20]:
# Exporting the cleaned dataset
df_clean.to_csv('df_clean.csv', index=False, encoding='utf-8')